modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/IAmREGE/CrNOBr/issues"

[[mods]]
modId="crnobr"
version="0.0.2"
displayName="CrNOBr"
description="Make creeper explosions not break blocks (unless you want)"
displayURL="https://github.com/IAmREGE/CrNOBr"
logoFile="icon.png"
authors="RheniumGermanide"
displayTest="IGNORE_ALL_VERSION"

[[mixins]]
config="crnobr.mixins.json"

[[dependencies.crnobr]]
modId="minecraft"
mandatory=true
versionRange="[1.20.5,)"
ordering="NONE"
side="BOTH"
